name: fetchAll 

on:
  push:
    branches:
      - 蹦蹦
  schedule:
    - cron:  '* * 1 * *'

jobs:
  fetchYears:
    runs-on: ubuntu-latest 
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
    - name: Fetch Years
      id: set-matrix
      run: python fetchYears.py 
  fetchYearData:
    needs: fetchYears
    runs-on: ubuntu-latest 
    if: ${{ always() }}
    strategy:
      matrix: ${{fromJson(needs.fetchYears.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
    - name: Fetch data (${{ matrix.years }})
      run: python runYear.py ${{ matrix.years }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.years }}
        path: ./dist/${{ matrix.years }}/
        retention-days: 2
  addMainJson:
    needs: fetchYearData
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with: 
        path: ./dist/
    - name: Show All years
      run: ls -R
      working-directory: ./dist/
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
    - name: Update main.json
      run: python updateMainJson.py
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist 
        keep_files: true