name: fetchAll 

on:
  push:
    branches:
      - 蹦蹦
  schedule:
    - cron:  '* * 1 * *'

jobs: 

  fetchYearData:
    needs: fetchYears
    runs-on: ubuntu-latest 
    if: ${{ always() }}
    strategy:
      matrix: [109,105]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
    - name: Fetch ${{ matrix.years }} data
      run: python runYear.py ${{ matrix.years }}
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist 
        keep_files: true
  addMainJson:
    needs: fetchYearData
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: dist
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
    - name: Update main.json
      run: python updateMainJson.py
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist 
        keep_files: true